import pandas as pd
import matplotlib.pyplot as plt

df_g1 = pd.read_csv('conjunction_benchmark_G1GC.csv')
df_zgc = pd.read_csv('conjunction_benchmark_ZGC.csv')
df_parallel = pd.read_csv('conjunction_benchmark_Parallel.csv')
df_shenandoah = pd.read_csv('conjunction_benchmark_Shenandoah.csv')

# Plot 1
fig, ax = plt.subplots(figsize=(10, 6))
ax.plot(df_g1['tolerance_km'], df_g1['total_s'], 'o-', color='#2E86AB', linewidth=2, markersize=8, label='G1GC')
ax.plot(df_zgc['tolerance_km'], df_zgc['total_s'], 's-', color='#D62839', linewidth=2, markersize=8, label='ZGC')
ax.plot(df_parallel['tolerance_km'], df_parallel['total_s'], '^-', color='#06A77D', linewidth=2, markersize=8, label='Parallel')
ax.plot(df_shenandoah['tolerance_km'], df_shenandoah['total_s'], 'd-', color='#F77F00', linewidth=2, markersize=8, label='Shenandoah')
min_time_idx_g1 = df_g1['total_s'].idxmin()
min_time_idx_zgc = df_zgc['total_s'].idxmin()
min_time_idx_parallel = df_parallel['total_s'].idxmin()
min_time_idx_shenandoah = df_shenandoah['total_s'].idxmin()
ax.axvline(x=df_g1.loc[min_time_idx_g1, 'tolerance_km'], color='#2E86AB', linestyle='--', linewidth=1, alpha=0.5)
ax.axvline(x=df_zgc.loc[min_time_idx_zgc, 'tolerance_km'], color='#D62839', linestyle='--', linewidth=1, alpha=0.5)
ax.axvline(x=df_parallel.loc[min_time_idx_parallel, 'tolerance_km'], color='#06A77D', linestyle='--', linewidth=1, alpha=0.5)
ax.axvline(x=df_shenandoah.loc[min_time_idx_shenandoah, 'tolerance_km'], color='#F77F00', linestyle='--', linewidth=1, alpha=0.5)
ax.set_xlabel('Tolerance (km)', fontsize=12)
ax.set_ylabel('Total Time (s)', fontsize=12)
ax.set_title('Total Processing Time vs Tolerance', fontsize=14, fontweight='bold')
ax.legend(fontsize=11)
ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('1_total_time.png', dpi=300, bbox_inches='tight')
plt.close()

# Plot 2
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))
ax1.plot(df_g1['tolerance_km'], df_g1['coarse_s'], 'o-', color='#2E86AB', linewidth=2, markersize=8, label='G1GC')
ax1.plot(df_zgc['tolerance_km'], df_zgc['coarse_s'], 's-', color='#D62839', linewidth=2, markersize=8, label='ZGC')
ax1.plot(df_parallel['tolerance_km'], df_parallel['coarse_s'], '^-', color='#06A77D', linewidth=2, markersize=8, label='Parallel')
ax1.plot(df_shenandoah['tolerance_km'], df_shenandoah['coarse_s'], 'd-', color='#F77F00', linewidth=2, markersize=8, label='Shenandoah')
ax1.set_xlabel('Tolerance (km)', fontsize=12)
ax1.set_ylabel('Time (s)', fontsize=12)
ax1.set_title('Coarse Processing Time', fontsize=14, fontweight='bold')
ax1.legend(fontsize=11)
ax1.grid(True, alpha=0.3)
ax2.plot(df_g1['tolerance_km'], df_g1['refine_s'], 'o-', color='#2E86AB', linewidth=2, markersize=8, label='G1GC')
ax2.plot(df_zgc['tolerance_km'], df_zgc['refine_s'], 's-', color='#D62839', linewidth=2, markersize=8, label='ZGC')
ax2.plot(df_parallel['tolerance_km'], df_parallel['refine_s'], '^-', color='#06A77D', linewidth=2, markersize=8, label='Parallel')
ax2.plot(df_shenandoah['tolerance_km'], df_shenandoah['refine_s'], 'd-', color='#F77F00', linewidth=2, markersize=8, label='Shenandoah')
ax2.set_xlabel('Tolerance (km)', fontsize=12)
ax2.set_ylabel('Time (s)', fontsize=12)
ax2.set_title('Refine Processing Time', fontsize=14, fontweight='bold')
ax2.legend(fontsize=11)
ax2.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('2_coarse_vs_refine.png', dpi=300, bbox_inches='tight')
plt.close()

# Plot 3
fig, (ax1, ax2, ax3, ax4) = plt.subplots(1, 4, figsize=(20, 5))
ax1.fill_between(df_g1['tolerance_km'], 0, df_g1['coarse_s'], label='Coarse', alpha=0.7, color='#06A77D')
ax1.fill_between(df_g1['tolerance_km'], df_g1['coarse_s'], df_g1['total_s'], label='Refine', alpha=0.7, color='#D62839')
ax1.set_xlabel('Tolerance (km)', fontsize=12)
ax1.set_ylabel('Time (s)', fontsize=12)
ax1.set_title('G1GC Processing Time Breakdown', fontsize=14, fontweight='bold')
ax1.legend(fontsize=11)
ax1.grid(True, alpha=0.3)
ax2.fill_between(df_zgc['tolerance_km'], 0, df_zgc['coarse_s'], label='Coarse', alpha=0.7, color='#06A77D')
ax2.fill_between(df_zgc['tolerance_km'], df_zgc['coarse_s'], df_zgc['total_s'], label='Refine', alpha=0.7, color='#D62839')
ax2.set_xlabel('Tolerance (km)', fontsize=12)
ax2.set_ylabel('Time (s)', fontsize=12)
ax2.set_title('ZGC Processing Time Breakdown', fontsize=14, fontweight='bold')
ax2.legend(fontsize=11)
ax2.grid(True, alpha=0.3)
ax3.fill_between(df_parallel['tolerance_km'], 0, df_parallel['coarse_s'], label='Coarse', alpha=0.7, color='#06A77D')
ax3.fill_between(df_parallel['tolerance_km'], df_parallel['coarse_s'], df_parallel['total_s'], label='Refine', alpha=0.7, color='#D62839')
ax3.set_xlabel('Tolerance (km)', fontsize=12)
ax3.set_ylabel('Time (s)', fontsize=12)
ax3.set_title('Parallel Processing Time Breakdown', fontsize=14, fontweight='bold')
ax3.legend(fontsize=11)
ax3.grid(True, alpha=0.3)
ax4.fill_between(df_shenandoah['tolerance_km'], 0, df_shenandoah['coarse_s'], label='Coarse', alpha=0.7, color='#06A77D')
ax4.fill_between(df_shenandoah['tolerance_km'], df_shenandoah['coarse_s'], df_shenandoah['total_s'], label='Refine', alpha=0.7, color='#D62839')
ax4.set_xlabel('Tolerance (km)', fontsize=12)
ax4.set_ylabel('Time (s)', fontsize=12)
ax4.set_title('Shenandoah Processing Time Breakdown', fontsize=14, fontweight='bold')
ax4.legend(fontsize=11)
ax4.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('3_time_breakdown.png', dpi=300, bbox_inches='tight')
plt.close()

# Plot 4
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))
ax1.plot(df_g1['tolerance_km'], df_g1['conj'], 'o-', color='#2E86AB', linewidth=2, markersize=8, label='G1GC')
ax1.plot(df_zgc['tolerance_km'], df_zgc['conj'], 's-', color='#D62839', linewidth=2, markersize=8, label='ZGC')
ax1.plot(df_parallel['tolerance_km'], df_parallel['conj'], '^-', color='#06A77D', linewidth=2, markersize=8, label='Parallel')
ax1.plot(df_shenandoah['tolerance_km'], df_shenandoah['conj'], 'd-', color='#F77F00', linewidth=2, markersize=8, label='Shenandoah')
ax1.set_xlabel('Tolerance (km)', fontsize=12)
ax1.set_ylabel('Conjunctions', fontsize=12)
ax1.set_title('Conjunctions Detected', fontsize=14, fontweight='bold')
ax1.legend(fontsize=11)
ax1.grid(True, alpha=0.3)

gcs = ['G1GC', 'ZGC', 'Parallel', 'Shenandoah']
avg_conj = [df_g1['conj'].mean(), df_zgc['conj'].mean(), df_parallel['conj'].mean(), df_shenandoah['conj'].mean()]
bars = ax2.bar(range(len(gcs)), avg_conj, color='#2E86AB', alpha=0.7)
ax2.set_xticks(range(len(gcs)))
ax2.set_xticklabels(gcs)
ax2.set_ylabel('Average Conjunctions', fontsize=12)
ax2.set_title('Average Conjunctions by GC', fontsize=14, fontweight='bold')
ax2.set_ylim(bottom=min(avg_conj) * 0.95)
ax2.grid(True, alpha=0.3, axis='y')
for bar, val in zip(bars, avg_conj):
    height = bar.get_height()
    ax2.text(bar.get_x() + bar.get_width()/2., height,
             f'{val:.1f}', ha='center', va='bottom', fontsize=10)

plt.tight_layout()
plt.savefig('4_conjunctions.png', dpi=300, bbox_inches='tight')
plt.close()